//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneDirect3DXamlAppInterop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneDirect3DXamlAppInterop.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store.support@outlook.com.
        /// </summary>
        public static string AboutContact {
            get {
                return ResourceManager.GetString("AboutContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact: .
        /// </summary>
        public static string AboutContactLabel {
            get {
                return ResourceManager.GetString("AboutContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is based on the source code provided by M.k, which is in turn based on the Snes9x source code. 
        ///
        ///The author is not responsible for any illegal use of this software. Furthermore, there is no warranty for this software and the author is not liable for any damages.
        ///
        ///Credits:
        ///- Eddi Bento for the logo.
        ///- Moga company for the surprised gift..
        /// </summary>
        public static string AboutSnes9x {
            get {
                return ResourceManager.GetString("AboutSnes9x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snes9x license:.
        /// </summary>
        public static string AboutSnes9xLicense {
            get {
                return ResourceManager.GetString("AboutSnes9xLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to use, copy, modify and/or distribute Snes9x in both binary and source form, for non-commercial purposes, is hereby granted without  fee, providing that this license information and copyright notice appear  with all copies and any derived work.  
        ///
        ///This software is provided &apos;as-is&apos;, without any express or implied warranty. In no event shall the authors be held liable for any damages arising from the use of this software or it&apos;s derivatives. 
        ///
        ///Snes9x is freeware for PERSONAL USE only. Commerci [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutSnes9xLicenseText {
            get {
                return ResourceManager.GetString("AboutSnes9xLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.snes9x.com/.
        /// </summary>
        public static string AboutSnes9xLink {
            get {
                return ResourceManager.GetString("AboutSnes9xLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snes9x homepage: .
        /// </summary>
        public static string AboutSnes9xLinkLabel {
            get {
                return ResourceManager.GetString("AboutSnes9xLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string aboutText {
            get {
                return ResourceManager.GetString("aboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (active).
        /// </summary>
        public static string ActiveSavestateText {
            get {
                return ResourceManager.GetString("ActiveSavestateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is already being downloaded..
        /// </summary>
        public static string AlreadyDownloadingText {
            get {
                return ResourceManager.GetString("AlreadyDownloadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snes8x.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound.
        /// </summary>
        public static string AudioSettingsPageTitle {
            get {
                return ResourceManager.GetString("AudioSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically increment save state.
        /// </summary>
        public static string AutoIncSavestateSetting {
            get {
                return ResourceManager.GetString("AutoIncSavestateSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image.
        /// </summary>
        public static string BackgroundImageSetting {
            get {
                return ResourceManager.GetString("BackgroundImageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export and import savegames:.
        /// </summary>
        public static string BackupAndRestoreInstructions {
            get {
                return ResourceManager.GetString("BackupAndRestoreInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string BackupButton {
            get {
                return ResourceManager.GetString("BackupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uploading a file: {0}. Try to sign out from SkyDrive and sign back in if this error persists..
        /// </summary>
        public static string BackupErrorUpload {
            get {
                return ResourceManager.GetString("BackupErrorUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To export saves, click on the name of the ROM in the list below. The savestates and SRAM will be uploaded to a SkyDrive directory. The save files are fully compatible with Snes8x for Windows 8/RT..
        /// </summary>
        public static string BackupInstructions {
            get {
                return ResourceManager.GetString("BackupInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export saves.
        /// </summary>
        public static string BackupPageTitle {
            get {
                return ResourceManager.GetString("BackupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting &apos;{0}&apos; saves.
        /// </summary>
        public static string BackupUploadProgressText {
            get {
                return ResourceManager.GetString("BackupUploadProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload completed..
        /// </summary>
        public static string BackupUploadSuccessful {
            get {
                return ResourceManager.GetString("BackupUploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload completed with errors..
        /// </summary>
        public static string BackupUploadUnsuccessful {
            get {
                return ResourceManager.GetString("BackupUploadUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the upload to complete..
        /// </summary>
        public static string BackupWaitForUpload {
            get {
                return ResourceManager.GetString("BackupWaitForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Button Scale.
        /// </summary>
        public static string ButtonScaleSettings {
            get {
                return ResourceManager.GetString("ButtonScaleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L-Button.
        /// </summary>
        public static string CameraAssignL {
            get {
                return ResourceManager.GetString("CameraAssignL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L-Button and R-Button.
        /// </summary>
        public static string CameraAssignLR {
            get {
                return ResourceManager.GetString("CameraAssignLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-Button.
        /// </summary>
        public static string CameraAssignR {
            get {
                return ResourceManager.GetString("CameraAssignR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbo Mode.
        /// </summary>
        public static string CameraAssignTurbo {
            get {
                return ResourceManager.GetString("CameraAssignTurbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to camera button.
        /// </summary>
        public static string CameraButtonAssignment {
            get {
                return ResourceManager.GetString("CameraButtonAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string ChooseBackgroundButtonText {
            get {
                return ResourceManager.GetString("ChooseBackgroundButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ClearBackgroundButtonText {
            get {
                return ResourceManager.GetString("ClearBackgroundButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this again.
        /// </summary>
        public static string ConfirmationCheckBoxText {
            get {
                return ResourceManager.GetString("ConfirmationCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmButtonText {
            get {
                return ResourceManager.GetString("ConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to load the last saved state?.
        /// </summary>
        public static string ConfirmLoadText {
            get {
                return ResourceManager.GetString("ConfirmLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save? This will overwrite the selected save state..
        /// </summary>
        public static string ConfirmSaveText {
            get {
                return ResourceManager.GetString("ConfirmSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Joystick Scale.
        /// </summary>
        public static string ControllerScaleSettings {
            get {
                return ResourceManager.GetString("ControllerScaleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating the backup folder..
        /// </summary>
        public static string CreateBackupFolderError {
            get {
                return ResourceManager.GetString("CreateBackupFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create snapshot for tiles.
        /// </summary>
        public static string CreateSnapshotMenuItem {
            get {
                return ResourceManager.GetString("CreateSnapshotMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadzone (analogue stick only).
        /// </summary>
        public static string DeadzoneHeader {
            get {
                return ResourceManager.GetString("DeadzoneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteMenuItemText {
            get {
                return ResourceManager.GetString("DeleteMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete save file.
        /// </summary>
        public static string DeleteSavesEntry {
            get {
                return ResourceManager.GetString("DeleteSavesEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donate.
        /// </summary>
        public static string DonateText {
            get {
                return ResourceManager.GetString("DonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed downloading file &apos;{0}&apos;.
        /// </summary>
        public static string DownloadCompleteText {
            get {
                return ResourceManager.GetString("DownloadCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading file &apos;{0}&apos; from SkyDrive: {1}.
        /// </summary>
        public static string DownloadErrorText {
            get {
                return ResourceManager.GetString("DownloadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading ROM &apos;{0}&apos;.
        /// </summary>
        public static string DownloadingProgressText {
            get {
                return ResourceManager.GetString("DownloadingProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-way.
        /// </summary>
        public static string DPad8way {
            get {
                return ResourceManager.GetString("DPad8way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dynamic analogue stick.
        /// </summary>
        public static string DPadAnalogueDynamic {
            get {
                return ResourceManager.GetString("DPadAnalogueDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed analogue stick.
        /// </summary>
        public static string DPadAnalogueFixed {
            get {
                return ResourceManager.GetString("DPadAnalogueFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-way.
        /// </summary>
        public static string DPadStandard {
            get {
                return ResourceManager.GetString("DPadStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D-Pad Style.
        /// </summary>
        public static string DPadStyleHeader {
            get {
                return ResourceManager.GetString("DPadStyleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide bar.
        /// </summary>
        public static string EmulatorBackIcon {
            get {
                return ResourceManager.GetString("EmulatorBackIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sound.
        /// </summary>
        public static string EnableSoundSetting {
            get {
                return ResourceManager.GetString("EnableSoundSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing and opening ROM file..
        /// </summary>
        public static string FileAssociationError {
            get {
                return ResourceManager.GetString("FileAssociationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to automatic.
        /// </summary>
        public static string FrameSkipAutoSetting {
            get {
                return ResourceManager.GetString("FrameSkipAutoSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Frames (increase emulation speed).
        /// </summary>
        public static string FrameSkipSetting {
            get {
                return ResourceManager.GetString("FrameSkipSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch to fullscreen.
        /// </summary>
        public static string FullscreenStretchOption {
            get {
                return ResourceManager.GetString("FullscreenStretchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string GeneralSettingsTitle {
            get {
                return ResourceManager.GetString("GeneralSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpButtonText {
            get {
                return ResourceManager.GetString("HelpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to import ROMs.
        /// </summary>
        public static string HelpDownloadROMsHeader {
            get {
                return ResourceManager.GetString("HelpDownloadROMsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how to.
        /// </summary>
        public static string HelpHowToHeader {
            get {
                return ResourceManager.GetString("HelpHowToHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative 2: importing from E-Mails.
        /// </summary>
        public static string HelpImportEmailHeader {
            get {
                return ResourceManager.GetString("HelpImportEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an E-Mail to any E-Mail address that is accessible from your phone, containing one or more ROM(s) as file attachments. You can either attach the ROMs as *.smc or *.sfc files or contained within a *.zip archive. Open the E-Mail on your phone and tap on the attachment to download the file. If your attachment was a *.zip archive, the E-Mail client allows you to navigate through the archive. Locate the ROM inside the archive and tap on it to launch the emulator. The emulator will automatically import the R [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpImportEmailText {
            get {
                return ResourceManager.GetString("HelpImportEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative 1: importing from SkyDrive.
        /// </summary>
        public static string HelpImportSkyDriveHeader {
            get {
                return ResourceManager.GetString("HelpImportSkyDriveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store your ROMs in a folder on your SkyDrive. If your ROMs are in *.zip file format, don&apos;t forget to extract them first, because Snes8x only supports *.smc and *.sfc files. Afterwards navigate to the SkyDrive section on the main page of the emulator (swipe left from the ROM list). If you are not signed in yet, click on &quot;Sign in&quot; first and enter your credentials if you are asked for it. When you are signed in, click on the button labeled &quot;import ROMs&quot; on the emulators main page. The following page allows you [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpImportSkyDriveText {
            get {
                return ResourceManager.GetString("HelpImportSkyDriveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative 3: importing from Web Browser.
        /// </summary>
        public static string HelpImportWebHeader {
            get {
                return ResourceManager.GetString("HelpImportWebHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In your web browser, open any web site that offers ROM downloads and start the download of the desired game. If the download was a *.zip archive, the browser allows you to navigate through the archive when the download is done. Locate the *.smc or *.sfc file contained in the archive and tap on it to start the emulator. The emulator will automatically import the ROM you downloaded using your web browser. If the downloaded file was a *.smc or *.sfc file, just tap on it and the emulator will start and import t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpImportWebText {
            get {
                return ResourceManager.GetString("HelpImportWebText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issues.
        /// </summary>
        public static string HelpIssuesHeader {
            get {
                return ResourceManager.GetString("HelpIssuesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank screen after loading ROM.
        /// </summary>
        public static string HelpIssuesWhiteScreenHeader {
            get {
                return ResourceManager.GetString("HelpIssuesWhiteScreenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Make sure the downloads are completed before you leave the SkyDrive import page (wait for confirmation message). If you leave too early, the ROMs may remain in a corrupted state and cannot load correctly. If this happens, delete them (tap and hold in the ROM list) and re-download.
        ///- Try other methods to import ROMs. There are 3 methods of importing ROMs (SkyDrive, E-Mail, Web Browser) described in the &quot;how to&quot; section of this page..
        /// </summary>
        public static string HelpIssuesWhiteScreenText {
            get {
                return ResourceManager.GetString("HelpIssuesWhiteScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - If nothing helps, contact the developer:.
        /// </summary>
        public static string HelpIssuesWhiteScreenTextContact {
            get {
                return ResourceManager.GetString("HelpIssuesWhiteScreenTextContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tips.
        /// </summary>
        public static string HelpTipsHeader {
            get {
                return ResourceManager.GetString("HelpTipsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games are running slowly.
        /// </summary>
        public static string HelpTipsPerformanceHeader {
            get {
                return ResourceManager.GetString("HelpTipsPerformanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Open the video settings and increase the value of the option &quot;Skip Frames (same emulation speed)&quot;. This option reduces the number of frames the emulator needs to display and therefore leaves more resources to keep the emulation speed up. The games might appear less smooth when increasing the frame skip value.
        ///- Open the sound settings and switch off audio synchronization. This might increase the performance, but the sound quality may suffer.
        ///- Open the sound settings and switch the sound completely off..
        /// </summary>
        public static string HelpTIpsPerformanceText {
            get {
                return ResourceManager.GetString("HelpTIpsPerformanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratchy sound.
        /// </summary>
        public static string HelpTipsSoundHeader {
            get {
                return ResourceManager.GetString("HelpTipsSoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Open the sound settings and switch on audio synchronization. This might increase the audio quality, but the performance may suffer.
        ///- If the emulation speed is too low, the sound quality can also suffer. Follow the above tips for games that are running slowly..
        /// </summary>
        public static string HelpTipsSoundText {
            get {
                return ResourceManager.GetString("HelpTipsSoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate turbo mode.
        /// </summary>
        public static string HelpTipsTurboHeader {
            get {
                return ResourceManager.GetString("HelpTipsTurboHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Press the camera button to toggle turbo mode.
        ///- Half-press the camera button to activate turbo mode while holding the camera button half-pressed..
        /// </summary>
        public static string HelpTipsTurboText {
            get {
                return ResourceManager.GetString("HelpTipsTurboText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable confirmation on load state.
        /// </summary>
        public static string HideConfirmationLoadSetting {
            get {
                return ResourceManager.GetString("HideConfirmationLoadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable confirmation on save state.
        /// </summary>
        public static string HideConfirmationSetting {
            get {
                return ResourceManager.GetString("HideConfirmationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Image (landscape only).
        /// </summary>
        public static string ImageScaleSetting {
            get {
                return ResourceManager.GetString("ImageScaleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import.
        /// </summary>
        public static string ImportButtonText {
            get {
                return ResourceManager.GetString("ImportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed importing file &apos;{0}&apos;.
        /// </summary>
        public static string ImportCompleteText {
            get {
                return ResourceManager.GetString("ImportCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import ROMs.
        /// </summary>
        public static string ImportFromSkyDriveButtonText {
            get {
                return ResourceManager.GetString("ImportFromSkyDriveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing ROM &apos;{0}&apos;.
        /// </summary>
        public static string ImportingProgressText {
            get {
                return ResourceManager.GetString("ImportingProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can play, it&apos;s necessary to upload ROMs to your SkyDrive folder. Afterwards click on &quot;Sign in&quot; to sign into SkyDrive. After signing in, click on &quot;import ROMs&quot; in order to import ROMs to your phone. .
        /// </summary>
        public static string ImportInstructionsText {
            get {
                return ResourceManager.GetString("ImportInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import&amp;export.
        /// </summary>
        public static string ImportTitle {
            get {
                return ResourceManager.GetString("ImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the download to complete..
        /// </summary>
        public static string ImportWaitComplete {
            get {
                return ResourceManager.GetString("ImportWaitComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input.
        /// </summary>
        public static string InputSettingsPageTitle {
            get {
                return ResourceManager.GetString("InputSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last played: .
        /// </summary>
        public static string LastPlayedLabel {
            get {
                return ResourceManager.GetString("LastPlayedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load state.
        /// </summary>
        public static string LoadStateButton {
            get {
                return ResourceManager.GetString("LoadStateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Refresh Rate.
        /// </summary>
        public static string LowFreqModeSetting {
            get {
                return ResourceManager.GetString("LowFreqModeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic .
        /// </summary>
        public static string ManageAutoSlotLabel {
            get {
                return ResourceManager.GetString("ManageAutoSlotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unknown error while removing the save state..
        /// </summary>
        public static string ManageDeleteUnknownError {
            get {
                return ResourceManager.GetString("ManageDeleteUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string ManageRemoveState {
            get {
                return ResourceManager.GetString("ManageRemoveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage save states.
        /// </summary>
        public static string ManageSavestateMenuItem {
            get {
                return ResourceManager.GetString("ManageSavestateMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save states.
        /// </summary>
        public static string ManageSavestatesTitle {
            get {
                return ResourceManager.GetString("ManageSavestatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string ManageSaveTimeLabel {
            get {
                return ResourceManager.GetString("ManageSaveTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot .
        /// </summary>
        public static string ManageSlotLabel {
            get {
                return ResourceManager.GetString("ManageSlotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tile pictures manually.
        /// </summary>
        public static string ManualSnapshotSetting {
            get {
                return ResourceManager.GetString("ManualSnapshotSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected ROM is pinned already or you have reached the maximum number of tiles to pin..
        /// </summary>
        public static string MaximumTilesPinned {
            get {
                return ResourceManager.GetString("MaximumTilesPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        public static string NeverPlayedText {
            get {
                return ResourceManager.GetString("NeverPlayedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not signed in. Sign in first to import ROMs from SkyDrive..
        /// </summary>
        public static string NotSignedInError {
            get {
                return ResourceManager.GetString("NotSignedInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Controller Opacity.
        /// </summary>
        public static string OpacitySetting {
            get {
                return ResourceManager.GetString("OpacitySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to landscape or portrait.
        /// </summary>
        public static string OrientationBoth {
            get {
                return ResourceManager.GetString("OrientationBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to landscape locked.
        /// </summary>
        public static string OrientationLandscape {
            get {
                return ResourceManager.GetString("OrientationLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portrait locked.
        /// </summary>
        public static string OrientationPortrait {
            get {
                return ResourceManager.GetString("OrientationPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        public static string OrientationSettingText {
            get {
                return ResourceManager.GetString("OrientationSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start screen.
        /// </summary>
        public static string PinToStartText {
            get {
                return ResourceManager.GetString("PinToStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Frames (same emulation speed).
        /// </summary>
        public static string PowerFrameSkipText {
            get {
                return ResourceManager.GetString("PowerFrameSkipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recently played.
        /// </summary>
        public static string RecentTitle {
            get {
                return ResourceManager.GetString("RecentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30Hz.
        /// </summary>
        public static string RefreshRate30 {
            get {
                return ResourceManager.GetString("RefreshRate30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60Hz.
        /// </summary>
        public static string RefreshRate60 {
            get {
                return ResourceManager.GetString("RefreshRate60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a save state first..
        /// </summary>
        public static string RemoveStateNoSelection {
            get {
                return ResourceManager.GetString("RemoveStateNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a name for the ROM..
        /// </summary>
        public static string RenameEmptyString {
            get {
                return ResourceManager.GetString("RenameEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string RenameMenuItemText {
            get {
                return ResourceManager.GetString("RenameMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ROM with that name already exists..
        /// </summary>
        public static string RenameNameAlreadyExisting {
            get {
                return ResourceManager.GetString("RenameNameAlreadyExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the displayed name of the ROM:.
        /// </summary>
        public static string RenamePromptMessage {
            get {
                return ResourceManager.GetString("RenamePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename ROM.
        /// </summary>
        public static string RenamePromptTitle {
            get {
                return ResourceManager.GetString("RenamePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string ResetROMButton {
            get {
                return ResourceManager.GetString("ResetROMButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import.
        /// </summary>
        public static string RestoreButton {
            get {
                return ResourceManager.GetString("RestoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select last state when loading ROM.
        /// </summary>
        public static string RestoreLastStateSetting {
            get {
                return ResourceManager.GetString("RestoreLastStateSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import saves.
        /// </summary>
        public static string RestorePageTitle {
            get {
                return ResourceManager.GetString("RestorePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume.
        /// </summary>
        public static string ResumeButtonText {
            get {
                return ResourceManager.GetString("ResumeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review.
        /// </summary>
        public static string ReviewText {
            get {
                return ResourceManager.GetString("ReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That ROM has been downloaded before: {0}.
        /// </summary>
        public static string ROMAlreadyExistingError {
            get {
                return ResourceManager.GetString("ROMAlreadyExistingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rom list.
        /// </summary>
        public static string RomListTitle {
            get {
                return ResourceManager.GetString("RomListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save state.
        /// </summary>
        public static string SaveStateButton {
            get {
                return ResourceManager.GetString("SaveStateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State 0.
        /// </summary>
        public static string SelectState0 {
            get {
                return ResourceManager.GetString("SelectState0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State 1.
        /// </summary>
        public static string SelectState1 {
            get {
                return ResourceManager.GetString("SelectState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State 2.
        /// </summary>
        public static string SelectState2 {
            get {
                return ResourceManager.GetString("SelectState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State 3.
        /// </summary>
        public static string SelectState3 {
            get {
                return ResourceManager.GetString("SelectState3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State 4.
        /// </summary>
        public static string SelectState4 {
            get {
                return ResourceManager.GetString("SelectState4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State 5.
        /// </summary>
        public static string SelectState5 {
            get {
                return ResourceManager.GetString("SelectState5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State 6.
        /// </summary>
        public static string SelectState6 {
            get {
                return ResourceManager.GetString("SelectState6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State 7.
        /// </summary>
        public static string SelectState7 {
            get {
                return ResourceManager.GetString("SelectState7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State 8.
        /// </summary>
        public static string SelectState8 {
            get {
                return ResourceManager.GetString("SelectState8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State 9.
        /// </summary>
        public static string SelectState9 {
            get {
                return ResourceManager.GetString("SelectState9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Auto State.
        /// </summary>
        public static string SelectStateAuto {
            get {
                return ResourceManager.GetString("SelectStateAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyDriveError: {0}.
        /// </summary>
        public static string SkyDriveError {
            get {
                return ResourceManager.GetString("SkyDriveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The emulator only supports *.smc and *.sfc files..
        /// </summary>
        public static string SkyDriveFileFormatHint {
            get {
                return ResourceManager.GetString("SkyDriveFileFormatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while accessing SkyDrive: {0}.
        /// </summary>
        public static string SkyDriveGeneralError {
            get {
                return ResourceManager.GetString("SkyDriveGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import ROMs.
        /// </summary>
        public static string SkyDriveImportTitle {
            get {
                return ResourceManager.GetString("SkyDriveImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to SkyDrive. Check your internet connection..
        /// </summary>
        public static string SkyDriveInternetLost {
            get {
                return ResourceManager.GetString("SkyDriveInternetLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceButtonText {
            get {
                return ResourceManager.GetString("SourceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sourceforge.net/projects/snes8x/.
        /// </summary>
        public static string SourceLink {
            get {
                return ResourceManager.GetString("SourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string StatusLabelContent {
            get {
                return ResourceManager.GetString("StatusLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not signed in..
        /// </summary>
        public static string StatusNotSignedIn {
            get {
                return ResourceManager.GetString("StatusNotSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signed in..
        /// </summary>
        public static string StatusSignedIn {
            get {
                return ResourceManager.GetString("StatusSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Audio.
        /// </summary>
        public static string SyncSoundSetting {
            get {
                return ResourceManager.GetString("SyncSoundSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (better quality, but may be slower).
        /// </summary>
        public static string SyncSoundSetting2 {
            get {
                return ResourceManager.GetString("SyncSoundSetting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the ROM associated with the tile..
        /// </summary>
        public static string TileOpenError {
            get {
                return ResourceManager.GetString("TileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbo Mode Frame Skip.
        /// </summary>
        public static string TurboFrameSkipText {
            get {
                return ResourceManager.GetString("TurboFrameSkipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Turbo Mode will be assigned to L or R if the camera button is assigned to L or R..
        /// </summary>
        public static string TurboModeTip {
            get {
                return ResourceManager.GetString("TurboModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting &apos;{0}&apos;.
        /// </summary>
        public static string UploadProgressText {
            get {
                return ResourceManager.GetString("UploadProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system accent color for live tile.
        /// </summary>
        public static string UseAccentBackgroundText {
            get {
                return ResourceManager.GetString("UseAccentBackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Moga controller.
        /// </summary>
        public static string UseMogaControllerText {
            get {
                return ResourceManager.GetString("UseMogaControllerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bottom.
        /// </summary>
        public static string VControllerBottomSetting {
            get {
                return ResourceManager.GetString("VControllerBottomSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intersecting.
        /// </summary>
        public static string VControllerLargeSetting {
            get {
                return ResourceManager.GetString("VControllerLargeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Controller Position.
        /// </summary>
        public static string VControllerPosSetting {
            get {
                return ResourceManager.GetString("VControllerPosSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Controller Buttons.
        /// </summary>
        public static string VControllerSizeSetting {
            get {
                return ResourceManager.GetString("VControllerSizeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dissecting.
        /// </summary>
        public static string VControllerSmallSetting {
            get {
                return ResourceManager.GetString("VControllerSmallSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top.
        /// </summary>
        public static string VControllerTopSetting {
            get {
                return ResourceManager.GetString("VControllerTopSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video.
        /// </summary>
        public static string VideoSettingsPageTitle {
            get {
                return ResourceManager.GetString("VideoSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colored.
        /// </summary>
        public static string VirtualControllerButtonColored {
            get {
                return ResourceManager.GetString("VirtualControllerButtonColored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gray.
        /// </summary>
        public static string VirtualControllerButtonGray {
            get {
                return ResourceManager.GetString("VirtualControllerButtonGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Controller Button Style.
        /// </summary>
        public static string VirtualControllerButtonStyle {
            get {
                return ResourceManager.GetString("VirtualControllerButtonStyle", resourceCulture);
            }
        }
    }
}
